# aulinha da udemy 

In [1]:
import numpy as np 
my_list = [1,2,3]

In [2]:
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3,],[4,5,6],[7,8,9]]

In [4]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
arr = np.zeros([3,3])

In [11]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.random.rand(5)

array([51.8259543 , 14.37437966, 85.53648294,  4.40198689, 79.02266497])

In [22]:
np.random.rand(5,4,3)

array([[[0.26332687, 0.6557344 , 0.14519922],
        [0.10174961, 0.53049835, 0.03058618],
        [0.45522498, 0.30897858, 0.99498771],
        [0.32156658, 0.1830906 , 0.67647109]],

       [[0.44324278, 0.9825011 , 0.85821991],
        [0.86777393, 0.63838727, 0.29747784],
        [0.15621781, 0.6745583 , 0.75615344],
        [0.25953397, 0.30474165, 0.98382662]],

       [[0.35373201, 0.77392723, 0.39955893],
        [0.38200243, 0.38484524, 0.4560782 ],
        [0.81544394, 0.45263206, 0.19246176],
        [0.76298424, 0.43081139, 0.10149922]],

       [[0.36442116, 0.27970863, 0.47571718],
        [0.14319592, 0.90939207, 0.40285214],
        [0.23707583, 0.95615765, 0.29985169],
        [0.0845804 , 0.04183286, 0.07002733]],

       [[0.70446924, 0.39844058, 0.0198198 ],
        [0.85347982, 0.44784081, 0.95478935],
        [0.2966998 , 0.68887387, 0.77902664],
        [0.50821056, 0.54612287, 0.81989556]]])

In [23]:
np.random.randn(4) # não sao tirados de distribuição uniforme

array([-0.3082194 ,  1.21435833,  0.7849401 ,  0.34687509])

In [25]:
np.random.randint(0,100,10)

array([13, 30, 47, 98, 16, 46, 99, 21, 35, 66])

In [28]:
np.round(np.random.rand(5)*100,0)

array([99., 12., 15., 53., 63.])

In [32]:
arr = np.random.rand(25)

In [33]:
arr

array([0.68958788, 0.60936245, 0.24046281, 0.60204278, 0.49696212,
       0.28533412, 0.17735001, 0.94874017, 0.47634711, 0.57245511,
       0.71952916, 0.55660236, 0.21473541, 0.96968944, 0.37243048,
       0.30903058, 0.24727416, 0.17330242, 0.78218596, 0.52358204,
       0.27408502, 0.9681492 , 0.51113431, 0.97311611, 0.78684664])

In [34]:
arr.reshape(5,5)

array([[0.68958788, 0.60936245, 0.24046281, 0.60204278, 0.49696212],
       [0.28533412, 0.17735001, 0.94874017, 0.47634711, 0.57245511],
       [0.71952916, 0.55660236, 0.21473541, 0.96968944, 0.37243048],
       [0.30903058, 0.24727416, 0.17330242, 0.78218596, 0.52358204],
       [0.27408502, 0.9681492 , 0.51113431, 0.97311611, 0.78684664]])

In [35]:
arr.shape # não´e método, é parâmetro do array

(25,)

In [37]:
arr.max()

0.9731161100620722

In [38]:
arr.max()

0.9731161100620722

In [40]:
arr.argmax()

23

In [43]:
arr.argmin()

17