In [ ]:
# Install TensorFlow
# !pip install -q tensorflow-gpu==2.0.0-beta1

try:
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
print(tf.__version__)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
2.15.0


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:

sentences = [
    "Eu gosto de sushi",
    "a cortina é branca",
    "to ferrado no trabalho"
    "Testzin com + texto"
    ""
]

In [ ]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [ ]:
print(sequences)
tokenizer.word_index

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12, 13, 14]]


{'eu': 1,
 'gosto': 2,
 'de': 3,
 'sushi': 4,
 'a': 5,
 'cortina': 6,
 'é': 7,
 'branca': 8,
 'to': 9,
 'ferrado': 10,
 'no': 11,
 'trabalhotestzin': 12,
 'com': 13,
 'texto': 14}

In [ ]:
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post')
print(data)

[[ 1  2  3  4  0  0]
 [ 5  6  7  8  0  0]
 [ 9 10 11 12 13 14]]


In [ ]:
MAX_SEQUENCE_LENGTH = 6
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, truncating = 'post')
print(data)
# as sequênciasforam truncadas no início

[[ 0  0  1  2  3  4]
 [ 0  0  5  6  7  8]
 [ 9 10 11 12 13 14]]
