In [1]:
import torch

In [3]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])

In [4]:
print(x.shape)

torch.Size([2, 4])


In [5]:
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [6]:
#soma
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [8]:
#Reshape
x.shape

torch.Size([2, 4])

In [9]:
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [10]:
#squeeze, remove uma dimensão do tensor
a = torch.ones(2,1,10)

In [11]:
#Tensor com 2 conjuntos, cada um com uma linha e 10 colunas
a


tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [12]:
print(f"shape antes do squeeze {a.shape}")
squeezed = a.squeeze(1)
print(f"shape depois do squeeze {squeezed.shape}")

shape antes do squeeze torch.Size([2, 1, 10])
shape depois do squeeze torch.Size([2, 10])


In [15]:
a = torch.ones(2,3,1)
print(f"este é o shape anetes do squeeze {a.shape}")
a
squeezed = a.squeeze(2)
print(f"essse é o shape depois do squeeze {squeezed.shape}")

este é o shape anetes do squeeze torch.Size([2, 3, 1])
essse é o shape depois do squeeze torch.Size([2, 3])


In [16]:
# unsqueeze, adiciona uma dimensão ao tensor
a = torch.ones(2,3)
print(f"shape antes do squeezing: {a.shape}")
squeezed = a.unsqueeze(2)
print(f"shape depois do squeeze {squeezed.shape}")

shape antes do squeezing: torch.Size([2, 3])
shape depois do squeeze torch.Size([2, 3, 1])


In [21]:
#adicionando falsas dimensões ao tensor em índices específicos
print(a[None].shape)
print(a[:,None].shape)
print(a[:,:,None].shape)
a.shape

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


torch.Size([2, 3])

Operações com matrizes:

In [22]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]]) # sformato = 2x3
y = torch.tensor([[1,2,3],
                  [2,3,4],
                  [4,5,6],
                  [7,8,9]]) #formato = 4x3

In [23]:
torch.matmul(x,y)

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [24]:
# Concatenação
x = torch.randn(1,4,5)
z = torch.cat([x,x], axis = 1)
print('eixo concatenado 1:', x.shape, z.shape)

eixo concatenado 1: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [26]:
#Permutação
x = torch.randn(3,20,10)
z = x.permute(2,0,1)
print('dimensões permutadas:',x.shape, z.shape)

dimensões permutadas: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
